name: Build Angular Client Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: List directory contents
        run: ls -la /home/runner/work/microfrontend/microfrontend

      - name: Configure npm to use GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" > ~/.npmrc
        
      - name: Install dependencies
        run: npm install 
        working-directory: /home/runner/work/microfrontend/microfrontend/src/ModuleFederation/Clients/Angular18Client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Build project
        run: npm run build
        working-directory: /home/runner/work/microfrontend/microfrontend/src/ModuleFederation/Clients/Angular18Client

      - name: dist List directory contents
        run: ls -la /home/runner/work/microfrontend/microfrontend/src/ModuleFederation/Clients/Angular18Client/dist
