name: Build & Publish MFELibrary to GitHub NPM Feed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          
      - name: List src directory contents
        run: ls -la /home/runner/work/microfrontend/microfrontend
        
      - name: Install dependencies
        run: npm install 
        working-directory: /home/runner/work/microfrontend/microfrontend/src/ModuleFederation/Libraries/MFELibrary

      - name: Build project
        run: npm run build
        working-directory: /home/runner/work/microfrontend/microfrontend/src/ModuleFederation/Libraries/MFELibrary

      - name: Run npm pack
        run: npm pack
        working-directory: /home/runner/work/microfrontend/microfrontend/src/ModuleFederation/Libraries/MFELibrary/dist

      - name: List dist directory contents
        run: ls -la /home/runner/work/microfrontend/microfrontend/src/ModuleFederation/Libraries/MFELibrary/dist

      - name: Set registry URL
        run: npm config set registry https://npm.pkg.github.com
        
      - name: Authenticate to GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" > ~/.npmrc
      
      - name: Check if package version exists
        id: check-package
        run: |
          PACKAGE_NAME=$(jq -r '.name' /home/runner/work/microfrontend/microfrontend/src/ModuleFederation/Libraries/MFELibrary/package.json)
          PACKAGE_VERSION=$(jq -r '.version' /home/runner/work/microfrontend/microfrontend/src/ModuleFederation/Libraries/MFELibrary/package.json)
          if npm view $PACKAGE_NAME@$PACKAGE_VERSION; then
            echo "Package version already exists."
            echo "::set-output name=package_exists::true"
          else
            echo "Package version does not exist."
            echo "::set-output name=package_exists::false"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Publish package
        if: steps.check-package.outputs.package_exists == 'false'
        run: npm publish
        working-directory: /home/runner/work/microfrontend/microfrontend/src/ModuleFederation/Libraries/MFELibrary/dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}
