# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - pcgitmfapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: List src directory contents
        run: Get-ChildItem -Force D:\a\microfrontend\microfrontend\src\services\webservice.services
        
      - name: Build with dotnet
        working-directory: D:\a\microfrontend\microfrontend\src\services\webservice.services
        run: dotnet build --configuration Release

      - name: List src directory contents
        run: Get-ChildItem -Force D:\a\microfrontend\microfrontend\src\services\webservice.services
        
      - name: dotnet publish
        working-directory: D:\a\microfrontend\microfrontend\src\services\webservice.services
        run: dotnet publish -c Release

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: D:\a\microfrontend\microfrontend\src\services\webservice.services\bin\Release\net9.0\publish\

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2126C4DAD59645DE8BC5DC5278A084A6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8FA95738EA6B44C28ACFB1296DC8810A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F75B9E7225C14CD0A848CA662D509AFB }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pcgitmfapi'
          slot-name: 'Production'
          package: .
          
